<?php
/**
 * Created by PhpStorm.
 * User: hasanov.r
 * Date: 05.09.2017
 * Time: 16:29
 */

namespace Application\Log;

use Doctrine\DBAL\Logging\DebugStack;
use Zend\Log\Logger;

class SqlLogger extends DebugStack
{
    protected $logger;
    public function __construct(Logger $logger)
    {
        $this->logger = $logger;
    }
    public function stopQuery()
    {
        parent::stopQuery(); // TODO: Change the autogenerated stub
        $q = $this->queries[$this->currentQuery];
        $message = "Executing query: " . print_r($q, true);
        $this->logger->info($message);
    }
}