<?php

namespace Users\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfirmationsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ConfirmationsRepository extends EntityRepository
{
}
