<?php

namespace RememberMe\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RememberMeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RememberMeRepository extends EntityRepository
{
    public function deleteByUid($uid)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->delete($this->_entityName,'r')
            ->where('r.user_id = :uid')
            ->setParameter('uid', $uid);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function deleteByUidAndSid($uid,$sid)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->delete($this->_entityName,'r')
            ->where('r.user_id = :uid')
            ->andWhere('r.sid = :sid')
            ->setParameter('uid', $uid)
            ->setParameter('sid', $sid);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
